### ISSUE TITLE
Adding child controls to e.g. a ListBox

### ISSUE THREAD

**Issue by daxfohl** [dmitry-a-morozov/fsharp-wpf-mvc-series#1]
If I wanted a `ListBox` filled with e.g. `StockSummary`s for each stock I've selected, the only way I see is to use a `DataTemplate` with the bindings defined in XAML strings.  Is there any more elegant typesafe solution for this?

**Comment by dmitry-a-morozov** [comment]
@daxfohl I cannot come up with reasonable implementation. I tried something similar to http://github.com/dmitry-a-morozov/fsharp-wpf-mvc-series/blob/master/Chapter%2012%20-%20BindingMicroDSL/FSharp.Windows/Binding.fs#L163
but DataTemplate is more tricky because it's a set of FrameworkElementFactory elements not FrameworkElements. I'll keep thinking but cannot promise anything at this point. Use data bindings in xaml for now.

**Comment by daxfohl** [comment]
@dmitry-a-morozov That's okay.  I'm feeling like reactjs is the future of functional GUI: https://www.youtube.com/watch?v=x7cQ3mrcKaY  Would be hard for WPF though since the markup itself is extensible with usercontrols etc, whereas HTML is fairly set.
